before_build:
  - nuget restore

after_build:
  -  cmd: msbuild TestingDeploy.xml /p:Configuration=Deploy;SolutionName=AppVeyor;ProjectName=TestWeb;OutputPath=C:\inetpub\wwwroot
  -  cmd: cd c:\inetpub\wwwroot
  -  cmd: dir
